[package]
name = "plctag-co"
version = "0.1.0"
authors = ["joylei <leingliu@gmail.com>"]
edition = "2018"

[dependencies]
plctag = { path = "../plctag" }
log = "*"
may = "*"
parking_lot = "*"
once_cell = "*"

[dev-dependencies]
anyhow = "*"
