[package]
name = "plctag"
version = "0.1.0"
authors = ["joylei <leingliu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
rustc-wrapper="sccache"

[features]
default=["async", "value"]
async=["parking_lot", "futures", "tokio", "lazy_static", "paste"]
value=["paste"]

[dependencies]
log="*"
parking_lot={version="*", optional=true}
futures ={version="*", optional=true}
tokio= {version="0.2.*", default-features=false, features=["rt-core", "blocking", "time"], optional=true}
paste={version="*", optional=true}
lazy_static={version="*", optional=true}

[build-dependencies]
bindgen="*"
