[package]
name = "plctag"
version = "0.1.0"
authors = ["joylei <leingliu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build]
rustc-wrapper="sccache"

[features]
default=["value", "controller"]
value=["paste"]
controller=["parking_lot"]

[dependencies]
log="*"
parking_lot={version="*", optional=true}
paste={version="*", optional=true}

[build-dependencies]
bindgen="*"
